Login page
ocadotechnology/codeforlife-contributor-frontend pull request #9
Opened 2024-08-30 11:30 UTC by SalmanAsh

2024-09-02 13:24 UTC, SKairinos requested changes

2024-09-02 13:24 UTC, SKairinos commented on src/pages/login/GitHub.tsx
> +    const urlParams = new URLSearchParams(window.location.search)
not like this. we have a hook which helps you do this.

```js
import { useSearchParams } from "codeforlife/hooks/router"
import * as yup from "yup"
...
const searchParams = useSearchParams({
code: yup.string()
})
...
if (searchParams?.code) {
    // DO STUFF
}
```

2024-09-02 13:24 UTC, SKairinos commented on src/pages/login/GitHub.tsx
> +      window.history.replaceState(null, "", window.location.pathname)
you must use the `useNavigate` hook to navigate between pages. you can only navigate after a component has mounted.

```js
import { useNavigate } from "codeforlife/hooks/router"
...
const navigate = useNavigate()
...
useEffect(() => {
// navigate to the same page with "."
navigate(".", { replace: true })
}, [...])
```

2024-09-02 13:24 UTC, SKairinos commented on src/pages/login/GitHub.tsx
> +          window.location.href = "/agreement-signatures"
navigate(paths.agreementSignatures._)

2024-09-02 13:24 UTC, SKairinos commented on src/pages/login/GitHub.tsx
> +          window.location.href = "/login"
You are already on the login page - there's no point in this.

2024-09-02 13:24 UTC, SKairinos commented on src/pages/login/GitHub.tsx
> +        <div
Delete this div. Use MUI's [Stack](https://mui.com/material-ui/react-stack/) instead. You can add spacing between element's using the Stack's spacing property.

2024-09-02 13:24 UTC, SKairinos commented on src/pages/login/GitHub.tsx
> +          <GitHubLoginButton />
Define button inline.

2024-09-02 13:24 UTC, SKairinos commented on src/routes/login.tsx
> +    <Route path={paths.login._} element={<GitHub />} />
<Route path={paths._} element={<Login />} />

2024-09-02 13:24 UTC, SKairinos commented on src/routes/paths.ts
> +  login: _("/login"),
delete this.

2024-09-02 13:24 UTC, SKairinos commented on src/pages/login/GitHub.tsx
delete this file and merge it's contents into the home page. the home will be our login page.

2024-09-02 13:24 UTC, SKairinos commented on src/pages/home/Home.tsx
>            This is an example of how you can create a web page. This example
remove this sample text and add some brief text welcoming CFL contributor's our contributor service and encouraging them to become a contributor.

2024-09-03 13:22 UTC, SalmanAsh reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9)* status: 0 of 28 files reviewed, 20 unresolved discussions (waiting on @SKairinos)

___
*[`src/pages/home/Home.tsx` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740923045:-O5n81_M6Rb3gewGRZ7V:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/pages/home/Home.tsx#L19)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove this sample text and add some brief text welcoming CFL contributor's our contributor service and encouraging them to become a contributor.
</blockquote></details>

Done.
___
*[`src/components/GitHubLoginButton.tsx` line 8 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740884671:-O5nGFaO16xMU_Dc5YO4:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/components/GitHubLoginButton.tsx#L8)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Do not need to be an independent, reusable component since it will only ever be rendered on the login page. Define this component inline in the login page and delete this file.
</blockquote></details>

Done.
___
*[`src/components/GitHubLoginButton.tsx` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740870153:-O5n4ul-0moV2_Iw21In:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/components/GitHubLoginButton.tsx#L13)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

sx = {theme => ({...})}
</blockquote></details>

Done.
___
*[`src/components/GitHubLoginButton.tsx` line 16 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740882155:-O5nGCp9Eir8OnNKpJi-:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/components/GitHubLoginButton.tsx#L16)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

don't use absolute values. use relative values.
```js
`${theme.spacing(4)} {theme.spacing(5)}`
```
[1 space = 8 pixels](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/main/src/theme/spacing.ts)

</blockquote></details>

Done.
___
*[`src/components/GitHubLoginButton.tsx` line 18 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740874814:-O5n54Cr85AcXywW6M3x:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/components/GitHubLoginButton.tsx#L18)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

try "black" or "black.main". if that doesn't work, try theme.palette.black.main
</blockquote></details>

Done.
___
*[`src/components/GitHubLoginButton.tsx` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740874415:-O5n54ws9ruAP6A3cIvg:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/components/GitHubLoginButton.tsx#L19)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

try `"white"` or `"white.main"`. if that doesn't work, try `theme.palette.white.main`
</blockquote></details>

Done.
___
*[`src/components/GitHubLoginButton.tsx` line 20 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740882095:-O5n56ry9OX1oDlKWwdW:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/components/GitHubLoginButton.tsx#L20)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why? doesn't seem necessary.
</blockquote></details>

Done.
___
*[`src/components/GitHubLoginButton.tsx` line 21 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740882068:-O5n57PF4YxBUhb3Q3u-:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/components/GitHubLoginButton.tsx#L21)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why? doesn't seem necessary.
</blockquote></details>

Done.
___
*[`src/components/GitHubLoginButton.tsx` line 24 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740869649:-O5n5cXI9AEwFy9SawC-:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/components/GitHubLoginButton.tsx#L24)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Use [this icon](https://mui.com/material-ui/material-icons/?query=github&selected=GitHub), not an image.
</blockquote></details>

Done.
___
*[`src/images/github-mark-white.png` line 0 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740885530:-O5n5hcO3QemSRSA_Bn-:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/images/github-mark-white.png#L0)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

delete this file. [use the icon that's already installed](https://mui.com/material-ui/material-icons/?query=github&selected=GitHub).
</blockquote></details>

Done.
___
*[`src/pages/login/GitHub.tsx` line 0 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740921277:-O5rN8R66upbEurNd_XH:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/pages/login/GitHub.tsx#L0)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

delete this file and merge it's contents into the home page. the home will be our login page.
</blockquote></details>

Done.
___
*[`src/pages/login/GitHub.tsx` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740898033:-O5s-p1K-hpF4hddUEjl:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/pages/login/GitHub.tsx#L14)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

not like this. we have a hook which helps you do this.

```js
import { useSearchParams } from "codeforlife/hooks/router"
import * as yup from "yup"
...
const searchParams = useSearchParams({
code: yup.string()
})
...
if (searchParams?.code) {
    // DO STUFF
}
```
</blockquote></details>

Done.
___
*[`src/pages/login/GitHub.tsx` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#gh-1740905449:-O5rQ1ZF6QAg3knUnpSu:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/9074bf52e6f62ca9b490886841804d469a2ed75b/src/pages/login/GitHub.tsx#L19)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

you must use the `useNavigate` hook to navigate between pages. you can only navigate after a component has mounted.

```js
import { useNavigate } from "codeforlife/hooks/router"
...
const navigate = useNavigate()
...
useEffect(() => {
// navigate to the same page with "."
navigate(" [...]

2024-09-06 11:01 UTC, SKairinos reviewed
> Reviewed 13 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9)* status: 13 of 28 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-09-06 11:15 UTC, SKairinos requested changes
> Reviewed 5 of 27 files at r1, 10 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9)* status: all files reviewed, 10 unresolved discussions (waiting on @SalmanAsh)

___
*[`.vscode/launch.json` line 21 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#-O65zpFr3s1FRTpyClhj:-O65zpFs1_iNMKa7Dkrn:bvtpy32) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/35e75b9f2949cef59ba08b3e8c195b128fd08c72/.vscode/launch.json#L21)):*
> ```JSON
>     },
>     {
>       "env": {
> ```

delete this
___
*[`src/api/session.ts` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#-O66-18b296UbFhNzCAM:-O66-18b296UbFhNzCAN:bw75muy) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/35e75b9f2949cef59ba08b3e8c195b128fd08c72/src/api/session.ts#L10)):*
> ```XML
> const sessionApi = api.injectEndpoints({
>   endpoints: build => ({
>     loginWithGitHub: build.mutation<LoginWithGitHubResult, LoginWithGitHubArg>({
> ```

just login
___
*[`src/app/env.ts` line 5 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#-O6607vN18Uk0u5_Y6f3:-O6607vN18Uk0u5_Y6f4:br8zgxe) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/35e75b9f2949cef59ba08b3e8c195b128fd08c72/src/app/env.ts#L5)):*
> ```XML
> export * from "codeforlife/env"
> 
> export const GH_CLIENT_ID = env.GITHUB_CLIENT_ID ?? "REPLACE_ME"
> ```

- make the entire link an env var
- add the env var in the .env file
- variable names must me the same
- env vars must start with "VITE_"
___
*[`src/pages/home/Home.tsx` line 1 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#-O660mAr4l7IOygrEKBU:-O660mAr4l7IOygrEKBV:bckjp6m) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/35e75b9f2949cef59ba08b3e8c195b128fd08c72/src/pages/home/Home.tsx#L1)):*
> ```XML
> import * as pages from "codeforlife/components/page"
> ```

fix imports
___
*[`src/pages/home/Home.tsx` line 34 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#-O661D_X1fwrL6WMMXbq:-O661D_X1fwrL6WMMXbr:b-c00urr) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/35e75b9f2949cef59ba08b3e8c195b128fd08c72/src/pages/home/Home.tsx#L34)):*
> ```XML
>       navigate(paths.agreementSignatures._)
>     } else if (code) {
>       navigate(".", { replace: true })
> ```

move this into the catch below.
___
*[`src/pages/home/Home.tsx` line 53 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#-O661MQY6nf1IiGJ0p8P:-O661MQY6nf1IiGJ0p8Q:b-u7m6pa) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/35e75b9f2949cef59ba08b3e8c195b128fd08c72/src/pages/home/Home.tsx#L53)):*
> ```XML
>         <Stack
>           spacing={10}
>           sx={{
> ```

us stack-level props
___
*[`src/pages/home/Home.tsx` line 73 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#-O661TH2AthKBbIVvgP3:-O661TH2AthKBbIVvgP4:b-g6ejo7) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/35e75b9f2949cef59ba08b3e8c195b128fd08c72/src/pages/home/Home.tsx#L73)):*
> ```XML
>             to={`https://github.com/login/oauth/authorize?client_id=${GH_CLIENT_ID}`}
>             sx={theme => ({
>               marginTop: `${theme.spacing(20)}`,
> ```

no need for the string here
___
*[`src/pages/home/Home.tsx` line 74 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#-O661_OQ6oCf-L0cZMZ_:-O661_OQ6oCf-L0cZMZa:b-g6ejo7) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/35e75b9f2949cef59ba08b3e8c195b128fd08c72/src/pages/home/Home.tsx#L74)):*
> ```XML
>             sx={theme => ({
>               marginTop: `${theme.spacing(20)}`,
>               borderRadius: `${theme.spacing(1)}`,
> ```

no need for the string here
___
*[`src/pages/home/Home.tsx` line 76 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#-O661_q3-s8aUtEtqWa8:-O661_q3-s8aUtEtqWa9:b-g6ejo7) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/35e75b9f2949cef59ba08b3e8c195b128fd08c72/src/pages/home/Home.tsx#L76)):*
> ```XML
>               borderRadius: `${theme.spacing(1)}`,
>               padding: `${theme.spacing(4)} ${theme.spacing(5)}`,
>               fontSize: `${theme.spacing(2.5)}`,
> ```

no need for the string here
___
*[`.env` line 2 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9#-O661ooo3xC1iVyZIcRv:-O661ooo3xC1iVyZIcRw:b-13ro87) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-frontend/blob/35e75b9f2949cef59ba08b3e8c195b128fd08c72/.env#L2)):*
> ```Dotenv
> # Service.
> VITE_SERVICE_NAME=contributor
> ```

add VITE_LINK_GH_LOGIN


<!-- Sent from Reviewable.io -->

2024-09-06 14:48 UTC, SKairinos approved these changes
> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-frontend/9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SalmanAsh)



<!-- Sent from Reviewable.io -->

2024-09-06 14:54 UTC, merged